### ISSUE TITLE
Sort corrupts css when rule contains multi-line comments

### ISSUE THREAD

**Issue by mmoore99** [madskristensen/CssSorter#1]
There appears to be a bug in the sort routine that causes css files to get corrupted when sorting rules that contain multi-line comments. The following "before" and "after" css file snippets illustrate the problem:
# Before sort:

``` css
#PoolDetails .sectionHeading {
    float: left;
    margin-top: 25px;
    margin-left: 50px;
    margin-bottom: 10px;
    /*clear: both;
    float: left;*/
}
```
# After sort:

``` css
#PoolDetails .sectionHeading {
    float: left;
    float: left;
    */; /*clear: both;margin-top: 25px;margin-bottom: 10px;margin-left: 50px;}
```
