### ISSUE TITLE
Sort All Properties removes scss mixin 

### ISSUE THREAD

**Issue by chadwells** [madskristensen/CssSorter#13]
This has happened a lot while working with the latest WE Nightly (2.0.11) on VS 2013 Update 2. 

The problem: when doing a Sort All Properties on an scss file (Shift-Alt-S), a mixin's implementation (the @include) is deleted from the code. The scss compiles fine before attempting to sort the properties.

To duplicate:

Create a new typescript project (not sure the type of project really matters)

Add new SCSS file, and put in the following code:

```
@mixin mediaQuery($breakpoint) {
    @media screen and (min-width: $breakpoint) {
        @content;
    }
}

#test {
    text-align: center;
    max-width: 1070px;

    @include mediaQuery(30em) {
        margin-top: 0.5em;
    }
}
```

Next, hit Shift-Alt-S, and notice the @include statement disappears.

**Comment by am11** [comment]
@spadapet, this library is used by WE.

My hunch was that this issue is somewhere at [Sorter.cs line 161-166](https://github.com/madskristensen/CssSorter/blob/master/CssSorter/Sorter.cs#L161-L166). I added `c is ScssIncludeDirective ||` to the mix, but no luck. With Update 2 overhaul, this code became bit messier -- redundant..

The biggest trouble with testing this project (as well as WE) is when a test need VSHost, it launches a VS instance on running/debugging tests and doesn't hit the breakpoint on debug. The LESS/SASS tests needs VSHost to resolve the content-type at runtime from editor (Line 107 and 115). Therefore, I need to copy paste the compiled dll each time in WE directory to test LESS/SASS related changes. 

CSS sorting tests, however, don't require VSHost and run in same instance so no issue debugging them..

Would you like to take a stab at it? :)

**Comment by spadapet** [comment]
Look at CssSortPropertiesCommandTarget.cs line 47 (I didn't look up how to make fancy links directly to the code). It only knows how to parse LESS and not SCSS, so you'll never see an ScssIncludeDirective.

By the way, it's disturbing that there is a hard coded list of item types that are allowed to be sorted in GetNormalizedText in Sorter.cs. The CSS tree is extensible so you can't predict all the different things that can be in it. Ideally there wouldn't be a filter in GetNormalizedText.

**Comment by am11** [comment]
Darn.... I never imagined that problem could be in WE code! Thanks for the review @spadapet :smile: 

BTW, the current implementation with flat string is wrong anyway. We should implement tree sort.

Currently, in a LESS/SASS file, if we have:

``` scss
#test {

   .two {
        text-align: center;
        max-width: 1070px;
    }
    .one {
        text-align: center;

        .one-point-one {
            text-align: center;
            max-width: 1070px;
        }
        max-width: 1070px;
    }

    text-align: center;
    max-width: 1070px;
}
```

It sorts only `.one-point-one` and `.two`. Whereas, the expected result is:

``` scss
#test {
    max-width: 1070px;
    text-align: center;

    .one {
        max-width: 1070px;
        text-align: center;

        .one-point-one {
            max-width: 1070px;
            text-align: center;
        }
    }

   .two {
        max-width: 1070px;
        text-align: center;
    }
}
```

We need to re-implement the whole thing with tree sort..
