### ISSUE TITLE
Still have problems with handling of comments

### ISSUE THREAD

**Issue by mmoore99** [madskristensen/CssSorter#3]
The changes that were put in place to resolve issue #1 seem to have addressed the issue of corrupting the file, but the way that comments are now being handled still does not appear to be correct.  See the sample below:
# Before Sort

``` css
#ResultsCentral #PickForm ul
{
    list-style: none;
    line-height: normal; 
    float: none;
    clear: none; /* inline comment 1 */
    /* list-style-type: none;
    list-style-position: inside; */
    margin: 0px 0px 15px 0px; /* multiline comment starting inline
    second line of multi-line comment */
    padding: 0px 0px 0px 0px;
}
```
# After Sort:

``` css
#ResultsCentral #PickForm ul {
    float: none;
    clear: none;
    margin: 0px 0px 15px 0px;
    padding: 0px 0px 0px 0px;
    list-style: none;
    line-height: normal; /* inline comment 1 */ /* list-style-type: none;
    list-style-position: inside; */ /* multiline comment starting inline
    second line of multi-line comment */
}
```

While pushing comments that are not inline to the bottom of the list seems ok, taking inline comments away from the declaration that they are associated with seems wrong.  In this example "inline comment 1" which was associated with the "clear: none;" declaration now shows on the "list-style-position" property line.  The multiline comment starting on the "margin" property line is also disassociated.
